"""修改了liuyanä¸å和comments字段

Revision ID: 44f682694fc7
Revises: cc3a03e096ec
Create Date: 2020-03-25 22:51:52.554846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44f682694fc7'
down_revision = 'cc3a03e096ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('send_time', sa.String(length=20), nullable=True))
    op.drop_column('comments', 'comment_time')
    op.add_column('liuyan', sa.Column('send_time', sa.String(length=20), nullable=True))
    op.drop_column('liuyan', 'liuyan_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liuyan', sa.Column('liuyan_time', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('liuyan', 'send_time')
    op.add_column('comments', sa.Column('comment_time', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('comments', 'send_time')
    # ### end Alembic commands ###
