"""updata04

Revision ID: 5e300dc2a5a2
Revises: 3226728a0ea5
Create Date: 2020-03-30 20:10:06.344086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e300dc2a5a2'
down_revision = '3226728a0ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_ibfk_1', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_ibfk_1', 'comments', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###
