"""给liuyan和comments添加了time字段

Revision ID: cc3a03e096ec
Revises: 79e33dcfc639
Create Date: 2020-03-25 16:43:06.266047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3a03e096ec'
down_revision = '79e33dcfc639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_time', sa.String(length=20), nullable=True))
    op.add_column('liuyan', sa.Column('liuyan_time', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liuyan', 'liuyan_time')
    op.drop_column('comments', 'comment_time')
    # ### end Alembic commands ###
