"""给post添加了文章图片连接字段

Revision ID: e876ed4abc08
Revises: 87b73b876512
Create Date: 2020-05-08 23:23:38.602325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e876ed4abc08'
down_revision = '87b73b876512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('pic_url', sa.String(length=100), nullable=True))
    op.alter_column('post', 'body',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('post', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               type_=sa.String(length=140),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=sa.String(length=140),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=140),
               existing_nullable=True)
    op.alter_column('post', 'body',
               existing_type=sa.Text(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.drop_column('post', 'pic_url')
    # ### end Alembic commands ###
